name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
#           target: x86_64-linux-android
#       - run: rustup target add x86_64-linux-android
#       - run: ls $ANDROID_HOME/ndk-bundle  
#       - run: ls /usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/  
      - run: make config
      - run: cat .cargo/config  
#       - run: make android  
      - run: cargo build --release --all-features
      - run: ls /home/runner/work/mikack-ffi/mikack-ffi/target/
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: /home/runner/work/mikack-ffi/mikack-ffi/target/  
#     steps:
#     - uses: actions/checkout@v2
#     - name: Build
#       run: cargo build --verbose
#     - name: Run tests
#       run: cargo test --verbose
